### ISSUE TITLE
Option to disable product photos

### ISSUE THREAD

**Issue by mindleak** [Cral-Cactus/woocommerce-discord-sale-notifications#2]
Just found and started using your plugin during my search to replace an old, incompatible one, love it!

However, the message is a little 'long' due to the product photo being shown.

Would it be possible to add an option/toggle to disable the product photo?

**Comment by Cral-Cactus** [comment]
@mindleak, thank you for the suggestion and sorry for the late reply! Yes I will make sure to add an option to disable product photo!

**Comment by Cral-Cactus** [comment]
I will release it probably within a week.

**Comment by Cral-Cactus** [comment]
@mindleak, I forgot to do PR and I directly pushed the update but it is alive - https://github.com/Cral-Cactus/wc-sale-discord-notifications/commit/0aa698faa27fd2f55c77a2703a41f9f6231974b1 !
Let me know how it is!

**Comment by mindleak** [comment]
@Cral-Cactus I'm sorry, I completely forgot to reply, lol, but got the update and it's great! Appreciate you adding that option! And thanks for making an awesome plugin. :)

**Comment by Cral-Cactus** [comment]
Glad to hear that! Enjoy!
